//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Data.Entities.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountWaiver
    {
        public int AccountWaiverId { get; set; }
        public int AccountId { get; set; }
        public int SignatureBlobId { get; set; }
        public int WaiverId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> EventId { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
