//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Data.Entities.DB
{
    using Microsoft.Extensions.Configuration;
    using System;
    using Microsoft.EntityFrameworkCore;


    public partial class dbsbltest1Entities : DbContext
    {
       
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            // connect to sql server database
            var ConnectionString = "Server=dbsbltest.database.windows.net;Database=dbsbltest1;username=dbsbltest; password=gwX7Nhy!UP3LeaKe";
            options.UseSqlServer(ConnectionString);
        }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountRole> AccountRole { get; set; }
        public virtual DbSet<Role> Role { get; set; }
    }
}
