//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Data.Entities.DB
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.SqlServer;

    public partial class dbsbltest1Entities : DbContext
    {
        public dbsbltest1Entities() : base(GetOptions())
        {
        }
        private static DbContextOptions GetOptions()
        {
            return SqlServerDbContextOptionsExtensions.UseSqlServer(new DbContextOptionsBuilder(), "dbsbltest1Entities").Options;
        }
       
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountRole> AccountRole { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<AccountWaiver> AccountWaiver { get; set; }
    
        public virtual ObjectResult<proc_GetAccountByPage_Result> proc_GetAccountByPage(Nullable<int> pageNo, Nullable<int> pageSize)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAccountByPage_Result>("proc_GetAccountByPage", pageNoParameter, pageSizeParameter);
        }
    }
}
